In [1]:
import pandas as pd
import numpy as np

In [3]:
# Import the data from a CSV file
date = pd.read_csv('../../data/orders.csv')
time = pd.read_csv('../../data/messages.csv')

## Working On data

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
date.drop(columns=['product_id', 'city_id', 'orders'], inplace=True)
date.head()

         date
0  2019-12-10
1  2018-08-15
2  2018-10-23
3  2019-08-17
4  2019-01-06

In [6]:
date.info() # date is pandas object , we need to convert it into datetime format

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [7]:
# Convert to datetime datatype
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

### 1. Extract Year

In [8]:
date['date_year'] = date['date'].dt.year
date.head()

        date  date_year
0 2019-12-10       2019
1 2018-08-15       2018
2 2018-10-23       2018
3 2019-08-17       2019
4 2019-01-06       2019

### 2. Extract Month

In [9]:
date['Month_num'] = date['date'].dt.month
date.head()

        date  date_year  Month_num
0 2019-12-10       2019         12
1 2018-08-15       2018          8
2 2018-10-23       2018         10
3 2019-08-17       2019          8
4 2019-01-06       2019          1

In [10]:
date['Month_name'] = date['date'].dt.month_name()
date.head()

        date  date_year  Month_num Month_name
0 2019-12-10       2019         12   December
1 2018-08-15       2018          8     August
2 2018-10-23       2018         10    October
3 2019-08-17       2019          8     August
4 2019-01-06       2019          1    January

### 3. Extract Day

In [11]:
date['Day'] = date['date'].dt.day
date.head()

        date  date_year  Month_num Month_name  Day
0 2019-12-10       2019         12   December   10
1 2018-08-15       2018          8     August   15
2 2018-10-23       2018         10    October   23
3 2019-08-17       2019          8     August   17
4 2019-01-06       2019          1    January    6

In [12]:
# Day of week
date['Day_of_week'] = date['date'].dt.dayofweek
date.head()

        date  date_year  Month_num Month_name  Day  Day_of_week
0 2019-12-10       2019         12   December   10            1
1 2018-08-15       2018          8     August   15            2
2 2018-10-23       2018         10    October   23            1
3 2019-08-17       2019          8     August   17            5
4 2019-01-06       2019          1    January    6            6

In [13]:
# Day of week (name)
date['Day_of_week_name'] = date['date'].dt.day_name()
date.head()

,date,date_year,Month_num,Month_name,Day,Day_of_week,Day_of_week_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [14]:
# Is weekend ?

date['Isweekned'] = np.where(date['Day_of_week_name'].isin(['Sunday', 'Saturday']), 1, 0)
date.head()

,date,date_year,Month_num,Month_name,Day,Day_of_week,Day_of_week_name,Isweekned
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

### 4. Extract Week Of Year

In [15]:
date['Week_of_year'] = date['date'].dt.isocalendar().week
date.head()

,date,date_year,Month_num,Month_name,Day,Day_of_week,Day_of_week_name,Isweekned,Week_of_year
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

### 5. Extract Quarter

In [16]:
date['Quarter'] = date['date'].dt.quarter
date.head()

,date,date_year,Month_num,Month_name,Day,Day_of_week,Day_of_week_name,Isweekned,Week_of_year,Quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

### 6. Extract Semester

In [17]:

date['Semester'] = np.where(date['Quarter'].isin([1,2]), 'First', 'Second')
date.head()

,date,date_year,Month_num,Month_name,Day,Day_of_week,Day_of_week_name,Isweekned,Week_of_year,Quarter,Semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,Second
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,Second
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,Second
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,Second
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,First

### 7. Extract Time elapsed b/w dates

In [18]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 9, 2, 22, 18, 16, 457487)

In [19]:
diff_date = (today - date['date'])
diff_date

0     2458 days 22:18:16.457487
1     2940 days 22:18:16.457487
2     2871 days 22:18:16.457487
3     2573 days 22:18:16.457487
4     2796 days 22:18:16.457487
                 ...
995   2886 days 22:18:16.457487
996   2827 days 22:18:16.457487
997   2675 days 22:18:16.457487
998   2740 days 22:18:16.457487
999   2514 days 22:18:16.457487
Name: date, Length: 1000, dtype: timedelta64[ns]

In [20]:
# Month Passed
np.round((today - date['date']).dt.days / 30.44, 0)

0      81.0
1      97.0
2      94.0
3      85.0
4      92.0
       ...
995    95.0
996    93.0
997    88.0
998    90.0
999    83.0
Name: date, Length: 1000, dtype: float64

## Working On Time

In [21]:
time.drop(columns=['msg'], inplace=True)
time.head()

                  date
0  2013-12-15 00:50:00
1  2014-04-29 23:40:00
2  2012-12-30 00:21:00
3  2014-11-28 00:31:00
4  2013-10-26 23:11:00

In [22]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [23]:
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

### 1. Extract hour, min and sec

In [24]:
time['time'] = time['date'].dt.time
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time['Date'] = time['date'].dt.date
time.head()

                 date      time  hour  min  sec        Date
0 2013-12-15 00:50:00  00:50:00     0   50    0  2013-12-15
1 2014-04-29 23:40:00  23:40:00    23   40    0  2014-04-29
2 2012-12-30 00:21:00  00:21:00     0   21    0  2012-12-30
3 2014-11-28 00:31:00  00:31:00     0   31    0  2014-11-28
4 2013-10-26 23:11:00  23:11:00    23   11    0  2013-10-26

### 2. Time Difference

In [25]:
# In Seconds
(today - time['date'])/ np.timedelta64(1, 's')

0      4.013189e+08
1      3.895727e+08
2      4.315606e+08
3      3.712528e+08
4      4.055584e+08
           ...
995    4.565285e+08
996    3.978687e+08
997    4.380433e+08
998    4.480659e+08
999    3.851672e+08
Name: date, Length: 1000, dtype: float64

In [26]:
# In Minutes
(today - time['date']) / np.timedelta64(1, 'm')

0      6.688648e+06
1      6.492878e+06
2      7.192677e+06
3      6.187547e+06
4      6.759307e+06
           ...
995    7.608808e+06
996    6.631144e+06
997    7.300721e+06
998    7.467764e+06
999    6.419453e+06
Name: date, Length: 1000, dtype: float64

In [27]:
# In Hours 
(today - time['date']) / np.timedelta64(1, 'h')

0      111477.471238
1      108214.637905
2      119877.954572
3      103125.787905
4      112655.121238
           ...
995    126813.471238
996    110519.071238
997    121678.687905
998    124462.737905
999    106990.887905
Name: date, Length: 1000, dtype: float64