## Opening a local CSV file

In [3]:
import pandas as pd
df = pd.read_csv('../data/aug_train.csv').head(5)
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [4]:
# Information about the data frame 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             5 non-null      int64
 1   city                    5 non-null      str
 2   city_development_index  5 non-null      float64
 3   gender                  3 non-null      str
 4   relevent_experience     5 non-null      str
 5   enrolled_university     4 non-null      str
 6   education_level         5 non-null      str
 7   major_discipline        5 non-null      str
 8   experience              5 non-null      str
 9   company_size            2 non-null      str
 10  company_type            3 non-null      str
 11  last_new_job            5 non-null      str
 12  training_hours          5 non-null      int64
 13  target                  5 non-null      float64
dtypes: float64(2), int64(2), str(10)
memory usage: 692.0 bytes

## Opening CSV from URL

In [5]:
import io
import requests

# Paste online link 
url = "https://raw.githubusercontent.com/MainakRepositor/Datasets-/master/zomato.csv"

# Setting headers prevents websites from blocking request
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
}

# Download the data from the website
req = requests.get(url, headers=headers)

# Use io.StringIO to convert the text data into an in-memory file object
data = io.StringIO(req.text)

# Load the file object straight into a pandas DataFrame
# Read the file using standard latin-1 encoding to prevent character errors
df = pd.read_csv(data, encoding="latin-1")

# Preview  imported online data
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

### Separate parameter

In [6]:
# .tsv --> Tab separated values

# Use sep='\t' --> separate data after tab
# pass str for creating header

df = pd.read_csv('../data/movie_titles_metadata.tsv', sep='\t', names = ['Number', 'about', 'year', 'score', 'limit', 'Genre' ])
df.head(5)

,Number,about,year,score,limit,Genre
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']

### Index parameter

In [7]:
# index_col --> removes pandas index
df = pd.read_csv('../data/electronic-card-trans.csv', index_col='Series_reference')
df.head(4)

,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
Series_reference,,,,,,,,,,,,,
ECTA.S19A1,2001.03,2462.5,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
ECTA.S19A1,2002.03,17177.2,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
ECTA.S19A1,2003.03,22530.5,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
ECTA.S19A1,2004.03,28005.1,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN

### Usecols parameter

In [8]:
# usecols = ['..', '...'] --> Extract specific columns

df = pd.read_csv('../data/movie_titles_metadata.tsv', sep='\t', names = ['Number', 'about', 'year', 'score', 'limit', 'Genre' ], usecols=['Number', 'year', 'score', 'limit'])
df.head(5)

  Number  year  score     limit
0     m0  1999    6.9   62847.0
1     m1  1992    6.2   10421.0
2     m2  2001    6.1   25854.0
3     m3  1968    8.4  163227.0
4     m4  1982    6.9   22289.0

### squeeze Parameter

In [9]:
""" To get the exact same behavior as squeeze=True (which forces a single-column DataFrame to become a Series), 
    append .squeeze() directly to the end.
"""

"""1. usecols=['enrollee_id', 'target'] --> loads a 2-column DataFrame.
   2. index_col='enrollee_id' --> moves the IDs to the row index, leaving exactly 1 column (target) in the main DataFrame body.
   3. squeeze() --> detects that single remaining data column and successfully collapses the whole object into a clean Pandas Series.
"""

df1 = pd.read_csv('../data/aug_train.csv',index_col='enrollee_id' ,usecols =['enrollee_id', 'target']).squeeze()
df1

enrollee_id
8949     1.0
29725    0.0
11561    0.0
33241    1.0
666      0.0
        ...
7386     1.0
31398    1.0
24576    0.0
5756     0.0
23834    0.0
Name: target, Length: 19158, dtype: float64

In [10]:

df1 = pd.read_csv('../data/aug_train.csv', usecols =['enrollee_id']).squeeze()
df1

0         8949
1        29725
2        11561
3        33241
4          666
         ...
19153     7386
19154    31398
19155    24576
19156     5756
19157    23834
Name: enrollee_id, Length: 19158, dtype: int64

## skiprows/nrows parameter

In [11]:
# skiprows --> skips the given number of rows

df2 = pd.read_csv('../data/customers.csv', index_col='Index', skiprows=[1,2]) # skips index 1 & 2
df2.index.name = None # remove the index name to avoid second line indexing 
df2.head(5)

,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
6,E1CDEaC63fDd5aA,Trevor,Lee,Maddox Group,Lake Madelineburgh,Senegal,+1-134-348-0265x9132,+1-313-882-4167,briangriffin@chang.org,2021-08-13,https://www.roberts.com/
7,3e1187fCcebC8d2,Mathew,Hoffman,"Bender, Pittman and Kidd",West Ralph,Uzbekistan,842.380.1168,(178)178-5447x32603,bauergerald@morrison.com,2020-04-09,http://www.holt.com/

In [12]:
# nrows --> used for chunking the data

df2 = pd.read_csv('../data/customers.csv', index_col='Index', nrows=100) # gives first 100 rows
df2.index.name = None # remove the index name to avoid second line indexing 
df2

,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
...,...,...,...,...,...,...,...,...,...,...,...
96,538Bdaef89F7672,Elaine,Hendrix,"Goodwin, Lambert and Lowery",South Veronicafurt,Fiji,3010334267,111-173-4785x11133,maureen18@barr.org,2020-12-24,http://mccarty-meza.info/
97,F231DF54939Fa4C,Marvin,Buchanan,Lowe-Mathis,Sheriville,Cuba,058-381-7608,+1-912-237-4307x878,ocole@sanders-lowery.net,2020-04-22,http://www.price.com/
98,5EDb197afE9965F,Paul,Moore,White-George,Marcoburgh,Brazil,(451)968-9182,+1-454-876-8759x02495,spencerbright@powell.biz,2021-12-10,https://wall-reid.com/
99,4f0B0BdAEDeC2F8,Grant,Tanner,Downs Group,Holdenchester,Chad,001-155-288-8390x9946,+1-073-135-3038x2148,dawncoffey@barker.com,2022-05-15,https://newton-esparza.net/
100,0eFf84b706a8DdB,Aimee,Sims,"Lara, Leon and Montoya",East Jeanneside,Grenada,(570)770-4667x7987,001-511-768-2295x52680,anthonyzuniga@tucker.com,2021-07-27,http://moran.com/

### dtype parameter

In [13]:
# dtype --> used to change to the data type of any columns
# target are using float(consume memory) --> can be converted into int
df3 = pd.read_csv('../data/aug_train.csv', dtype={'target':'int8'})
df3.head(4)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1

In [14]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  str
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  str
 4   relevent_experience     19158 non-null  str
 5   enrolled_university     18772 non-null  str
 6   education_level         18698 non-null  str
 7   major_discipline        16345 non-null  str
 8   experience              19093 non-null  str
 9   company_size            13220 non-null  str
 10  company_type            13018 non-null  str
 11  last_new_job            18735 non-null  str
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int8
dtypes: float64(1), int64(2), int8(1), str(10)
memory usage: 1.9 MB

### dates

In [ ]:
# Given data consider 'date' as string --> can't use date filter
df_ipl = pd.read_csv('../data/IPL.csv')
df_ipl.info()

/var/folders/t6/83ml_h093hb2vy010z1bgz_m0000gn/T/ipykernel_4179/1002236460.py:1: DtypeWarning: Columns (0: review_batter, 1: team_reviewed, 2: review_decision, 3: umpire, 4: season, 5: superover_winner, 6: result_type, 7: method, 8: event_match_no) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ipl = pd.read_csv('../data/IPL.csv')

<class 'pandas.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         283678 non-null  int64
 1   match_id           283678 non-null  int64
 2   date               283678 non-null  str
 3   match_type         283678 non-null  str
 4   event_name         283678 non-null  str
 5   innings            283678 non-null  int64
 6   batting_team       283678 non-null  str
 7   bowling_team       283678 non-null  str
 8   over               283678 non-null  int64
 9   ball               283678 non-null  int64
 10  ball_no            283678 non-null  float64
 11  batter             283678 non-null  str
 12  bat_pos            283678 non-null  int64
 13  runs_batter        283678 non-null  int64
 14  balls_faced        283678 non-null  int64
 15  bowler             283678 non-null  str
 16  valid_ball         283678 non-null  int64
 17  runs_extras        283678 non-null  int64
 18  runs_total         283678 non-null  int64
 19  runs_bowler        283678 non-null  int64
 20  runs_not_boundary  283678 non-null  bool
 21  extra_type         15493 non-null   str
 22  non_striker        283678 non-null  str
 23  non_striker_pos    283678 non-null  int64
 24  wicket_kind        14106 non-null   str
 25  player_out         14106 non-null   str
 26  fielders           10245 non-null   str
 27  runs_target        136510 non-null  float64
 28  review_batter      907 non-null     str
 29  team_reviewed      907 non-null     str
 30  review_decision    907 non-null     str
 31  umpire             907 non-null     str
 32  umpires_call       283678 non-null  bool
 33  player_of_match    283678 non-null  str
 34  match_won_by       283678 non-null  str
 35  win_outcome        278954 non-null  str
 36  toss_winner        283678 non-null  str
 37  toss_decision      283678 non-null  str
 38  venue              283678 non-null  str
 39  city               283678 non-null  str
 40  day                283678 non-null  int64
 41  month              283678 non-null  int64
 42  year               283678 non-null  int64
 43  season             283678 non-null  object
 44  gender             283678 non-null  str
 45  team_type          283678 non-null  str
 46  superover_winner   3896 non-null    str
 47  result_type        4724 non-null    str
 48  method             3890 non-null    str
 49  balls_per_over     283678 non-null  int64
 50  overs              283678 non-null  int64
 51  event_match_no     283678 non-null  object
 52  stage              283678 non-null  str
 53  match_number       283678 non-null  str
 54  team_runs          283678 non-null  int64
 55  team_balls         283678 non-null  int64
 56  team_wicket        283678 non-null  int64
 57  new_batter         13593 non-null   str
 58  power_surge_start  0 non-null       float64
 59  batter_runs        283678 non-null  int64
 60  batter_balls       283678 non-null  int64
 61  bowler_wicket      283678 non-null  int64
 62  batting_partners   283678 non-null  str
 63  next_batter        13593 non-null   str
 64  striker_out        283678 non-null  bool
dtypes: bool(3), float64(3), int64(24), object(2), str(33)
memory usage: 135.0+ MB

In [ ]:
# typecasting into datetime64
df_ipl = pd.read_csv('../data/IPL.csv',parse_dates=['date']).info()

/var/folders/t6/83ml_h093hb2vy010z1bgz_m0000gn/T/ipykernel_4179/3931941005.py:1: DtypeWarning: Columns (0: review_batter, 1: team_reviewed, 2: review_decision, 3: umpire, 4: season, 5: superover_winner, 6: result_type, 7: method, 8: event_match_no) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ipl = pd.read_csv('../data/IPL.csv',parse_dates=['date']).info()

<class 'pandas.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         283678 non-null  int64
 1   match_id           283678 non-null  int64
 2   date               283678 non-null  datetime64[us]
 3   match_type         283678 non-null  str
 4   event_name         283678 non-null  str
 5   innings            283678 non-null  int64
 6   batting_team       283678 non-null  str
 7   bowling_team       283678 non-null  str
 8   over               283678 non-null  int64
 9   ball               283678 non-null  int64
 10  ball_no            283678 non-null  float64
 11  batter             283678 non-null  str
 12  bat_pos            283678 non-null  int64
 13  runs_batter        283678 non-null  int64
 14  balls_faced        283678 non-null  int64
 15  bowler             283678 non-null  str
 16  valid_ball         283678 non-null  int64
 17  runs_extras        283678 non-null  int64
 18  runs_total         283678 non-null  int64
 19  runs_bowler        283678 non-null  int64
 20  runs_not_boundary  283678 non-null  bool
 21  extra_type         15493 non-null   str
 22  non_striker        283678 non-null  str
 23  non_striker_pos    283678 non-null  int64
 24  wicket_kind        14106 non-null   str
 25  player_out         14106 non-null   str
 26  fielders           10245 non-null   str
 27  runs_target        136510 non-null  float64
 28  review_batter      907 non-null     str
 29  team_reviewed      907 non-null     str
 30  review_decision    907 non-null     str
 31  umpire             907 non-null     str
 32  umpires_call       283678 non-null  bool
 33  player_of_match    283678 non-null  str
 34  match_won_by       283678 non-null  str
 35  win_outcome        278954 non-null  str
 36  toss_winner        283678 non-null  str
 37  toss_decision      283678 non-null  str
 38  venue              283678 non-null  str
 39  city               283678 non-null  str
 40  day                283678 non-null  int64
 41  month              283678 non-null  int64
 42  year               283678 non-null  int64
 43  season             283678 non-null  object
 44  gender             283678 non-null  str
 45  team_type          283678 non-null  str
 46  superover_winner   3896 non-null    str
 47  result_type        4724 non-null    str
 48  method             3890 non-null    str
 49  balls_per_over     283678 non-null  int64
 50  overs              283678 non-null  int64
 51  event_match_no     283678 non-null  object
 52  stage              283678 non-null  str
 53  match_number       283678 non-null  str
 54  team_runs          283678 non-null  int64
 55  team_balls         283678 non-null  int64
 56  team_wicket        283678 non-null  int64
 57  new_batter         13593 non-null   str
 58  power_surge_start  0 non-null       float64
 59  batter_runs        283678 non-null  int64
 60  batter_balls       283678 non-null  int64
 61  bowler_wicket      283678 non-null  int64
 62  batting_partners   283678 non-null  str
 63  next_batter        13593 non-null   str
 64  striker_out        283678 non-null  bool
dtypes: bool(3), datetime64[us](1), float64(3), int64(24), object(2), str(32)
memory usage: 135.0+ MB

### convertors

In [ ]:

# Add low_memory=False 
# Tells Pandas to read the entire file at once instead of in chunks, 
# allowing it to correctly guess the right data type for every single column without guessing incorrectly.
df_ipl = pd.read_csv('../data/IPL.csv', low_memory=False)
df_ipl.head(5)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [25]:
df_ipl = pd.read_csv('../data/IPL.csv', low_memory=False, usecols=['batting_team']).squeeze()
# Returns an array of non-repeating strings
df_ipl.unique()

<StringArray>
[      'Kolkata Knight Riders', 'Royal Challengers Bangalore',
         'Chennai Super Kings',             'Kings XI Punjab',
            'Rajasthan Royals',            'Delhi Daredevils',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
        'Lucknow Super Giants',              'Gujarat Titans',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str

In [31]:
df_ipl = pd.read_csv('../data/IPL.csv', low_memory=False, usecols=['event_name']).squeeze()
# Returns an array of non-repeating strings
df_ipl.unique()

<StringArray>
['Indian Premier League']
Length: 1, dtype: str

In [ ]:
# Defining mapping dictionary for the teams
team_map = {
    "Royal Challengers Bangalore": "RCB",
    "Royal Challengers Bengaluru": "RCB",
    "Mumbai Indians": "MI",
    "Chennai Super Kings": "CSK",
    "Kolkata Knight Riders": "KKR",
    "Rajasthan Royals": "RR",
    "Delhi Capitals": "DC",
    "Delhi Daredevils": "DC",
    "Kings XI Punjab": "KXIP",
    "Punjab Kings": "PBKS",
    "Sunrisers Hyderabad": "SRH",
    "Deccan Chargers": "DCG",
    "Gujarat Titans": "GT",
    "Lucknow Super Giants": "LSG",
}

# Creating a converter function that replaces names or falls back to the original
def shorten_team(team_name):
    # .strip() removes accidental leading/trailing spaces
    return team_map.get(team_name.strip(), team_name)

import pandas as pd

# If the text matches (even with spaces), change it to 'IPL', otherwise keep original
ipl_converter = lambda text: "IPL" if text.strip().lower() == "indian premier league" else text


#  Read the file passing your function into the converters dictionary
df_ipl = pd.read_csv("../data/IPL.csv", low_memory=False, parse_dates=['date'], converters={"batting_team": shorten_team, "bowling_team":shorten_team, "event_name": ipl_converter})


# 4. Check the unique shortened names
df_ipl.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,IPL,1,KKR,RCB,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,IPL,1,KKR,RCB,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,IPL,1,KKR,RCB,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,IPL,1,KKR,RCB,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,IPL,1,KKR,RCB,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

### na_parameter

In [39]:
df = pd.read_csv('../data/aug_train.csv')
df.head(5)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [40]:
df = pd.read_csv('../data/aug_train.csv', na_values=['No relevent experience'])
df.head(5)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,NaN,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,NaN,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,NaN,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

### chuck size

In [88]:
reader = pd.read_csv('../data/BX-Books.csv', sep=";", encoding='latin-1', on_bad_lines="skip", low_memory=False, chunksize=50000)
# Fix 1: Explicitly use semicolons
# Fix 2: Prevent character decoding crashes
# Fix 3: Skip lines with corrupt/unescaped quotes


for chunk in reader:
    df_first_chunk = chunk
    break
df_first_chunk.head()

,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/0195153448.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
1,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
2,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
3,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
4,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...

In [89]:
for chunk in reader:
    print(f"chunk size : {chunk.size} | shape : {chunk.shape}")

chunk size : 400000 | shape : (50000, 8)
chunk size : 400000 | shape : (50000, 8)
chunk size : 400000 | shape : (50000, 8)
chunk size : 400000 | shape : (50000, 8)
chunk size : 170872 | shape : (21359, 8)